name       : haskell-attoparsec
version    : 0.13.0.2
release    : 1
source     :
    - http://hackage.haskell.org/package/attoparsec-0.13.0.2/attoparsec-0.13.0.2.tar.gz : 69f7f381f644ba4a6f348bbff9b2b4280b7b602e8e25e59eadb6e30ad5f2ec6a
license    : BSD-3-Clause
component  : programming
summary    : A fast parser combinator library, aimed particularly at dealing efficiently with network protocols and complicated text/binary file formats. 
description: |
    A fast parser combinator library, aimed particularly at dealing efficiently with network protocols and complicated text/binary file formats. 
builddeps  :
    - ghc
    - haskell-scientific
    - haskell-text
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 attoparsec-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/attoparsec-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/attoparsec-$version/*.a
