name       : haskell-attoparsec
version    : 0.13.2.2
release    : 4
source     :
    - https://hackage.haskell.org/package/attoparsec-0.13.2.2/attoparsec-0.13.2.2.tar.gz : dd93471eb969172cc4408222a3842d867adda3dd7fb39ad8a4df1b121a67d848
license    : BSD-3-Clause
component  : programming.haskell
summary    : A fast parser combinator library, aimed particularly at dealing efficiently with network protocols and complicated text/binary file formats.
description: |
    A fast parser combinator library, aimed particularly at dealing efficiently
    with network protocols and complicated text/binary file formats.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-scientific
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
