name       : haskell-attoparsec
version    : 0.13.0.2
release    : 2
source     :
    - http://hackage.haskell.org/package/attoparsec-0.13.0.2/attoparsec-0.13.0.2.tar.gz : 69f7f381f644ba4a6f348bbff9b2b4280b7b602e8e25e59eadb6e30ad5f2ec6a
license    : BSD-3-Clause
component  : programming.haskell
summary    : A fast parser combinator library, aimed particularly at dealing efficiently
    with network protocols and complicated text/binary file formats.
description: "A fast parser combinator library, aimed particularly at dealing efficiently\
    \ with network protocols and complicated text/binary file formats. \n"
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-scientific
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
