name       : haskell-attoparsec
version    : 0.13.2.4
release    : 5
source     :
    - https://hackage.haskell.org/package/attoparsec-0.13.2.4/attoparsec-0.13.2.4.tar.gz : ba66cd6de1749ec92568db1b9c905b43a849f0ad918d45d7b594407a02ebefb2
license    : BSD-3-Clause
component  : programming.haskell
summary    : A fast parser combinator library, aimed particularly at dealing efficiently with network protocols and complicated text/binary file formats.
description: |
    A fast parser combinator library, aimed particularly at dealing efficiently with network protocols and complicated text/binary file formats.
builddeps  :
    - haskell-cabal-install
    - haskell-scientific-devel
rundeps    :
    - devel:
        - haskell-scientific-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
